config/routes.rb
Rails.application.routes.draw do

  resources :cities do
    resources :spots do
      resources :comments
    end
  end

  devise_for :users

  root to: 'cities#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :spots
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :spot
  belongs_to :user
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :city, optional: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :spots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end


  def show
    @city = City.find(params[:city_id])
    @spot = Spot.find(params[:id])
    @comment = Comment.find(params[:id])
  end


  def new
    @city = City.find(params[:city_id])
    @spot = Spot.new
    @comment = Comment.new
  end


  def edit
    @spot = Spot.find(params[:spot_id])
    @comment = Comment.find(params[:id])
  end


  def create
    @city = City.find(params[:city_id])
    @spot = Spot.find(params[:spot_id])
    @comment = @spot.comments.build(params[:comment].permit(:body))
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to city_spot_path(@city, @spot), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
    # redirect_to city_spot_path(@spot)
  end


  def update
    @comment = Comment.find(params[:id])
    @comment.assign_attributes(comment_params)

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @city = City.find(params[:city_id])
    @spot = Spot.find(params[:spot_id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to city_spot_path(@city, @spot), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:spot_id, :user_id, :body)
    end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  # before_action :set_spot, only: [:show, :edit, :update, :destroy]

  def index
    @spots = Spot.all
  end

  def show
    @city = City.find(params[:city_id])
    @spot = Spot.find(params[:id])
  end

  def new
    @city = City.find(params[:city_id])
    @spot = Spot.new
  end

  def edit
    @city = City.find(params[:city_id])
    @spot = Spot.find(params[:id])
  end

  def create
    @city = City.find(params[:city_id])
    @spot = @city.spots.build(spot_params)
    @spot.user = current_user

    respond_to do |format|
      if @spot.save
        format.html { redirect_to city_spot_path(@city, @spot), notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
    # redirect_to @city
  end

  def update
    @spot = Spot.find(params[:id])
    @spot.assign_attributes(spot_params)

    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to city_spot_path(@spot.city, @spot), notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    # redirect_to [@spot.city, @spot]
    end
  end


  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:name, :description, :city_id, :user_id, :image_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :city_name %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :city_state %>
  </div>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :city_user_id %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<% i = 0 %>
<% if @cities.count % 3 == 0 %>
  <% rows = (cities / 3) %>
<% else %>
  <% rows = ((@cities.count / 3) + 1) %>
<% end %>
<% rows.times do %>
  <div class="city_row">
    <% @cities[i..(i+2)].each do |city| %>
      <%= link_to city, class: "city_link" do %>
        <div class="city_img" style="background-image:url('<%= city.image_url %>')"><p><%= city.name %></p></div>
      <% end %>
    <% end %>
  </div>
  <% i += 3 %>
<% end %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<div id='banner' style="background-image:url('<%= @city.image_url %>')">
  <!-- <div id='nav_links'>Sample text</div> -->
  <div id='gradient'></div>
  <div id='banner_text'>
    <%= @city.name %>, <%= @city.state %>
  </div>
</div>

<div id='spot_info'>
  <h2><%= @city.spots.count %> Spots listed in <%= @city.name %>:</h2>
  <p id="new_spot_link">Submit a New Spot</p>

  <div id="new_spot_form">
    <% if user_signed_in? %>

      <div id='form_title'>
        Know a Spot in <%= @city.name %>?
      </div>

      <div id='form_fields'>
        <%= form_for [@city, Spot.new] do |f| %>
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, placeholder: "What's the Spot's name?", :size => "32" %>
          </div>

          <div class="field">
            <%= f.label :image_url %>
            <%= f.text_field :image_url, placeholder: "Enter image link URL", :size => "32" %>
          </div>

          <div class="field">
            <%= f.label :description %>
            <%= f.text_area :description, placeholder: "Tell us about this Spot", cols: 32, rows: 6 %>
          </div>

          <div class="field">
            <%= f.submit %>
            <div id='cancel_btn'>Cancel</div>
          </div>
        </div>

        <div id='form_guidelines'>
          <p> Spot Submission Guidelines:</p>
          <ul>
            <li>Submit only spots that you have been to.</li>
            <li>Explain what the spot is, and who might be interested in going there.</li>
            <li>Refrain from vulgar language and negative reviews. City Spots is for exposé, not bashing businesses.</li>
          </ul>
        </div>
      <% end %>  <!-- end form_for -->

    <% end %>    <!-- end `if user_signed_in` -->

  </div>


  <!-- set the correct number of rows with a loop -->
  <% i = 0 %>
  <% if @city.spots.count % 5 == 0 %>
    <% rows = (@city.spots.count / 5) %>
  <% else %>
    <% rows = ((@city.spots.count / 5) + 1) %>
  <% end %>

  <!-- populate the rows with image links  -->
  <% rows.times do %>
    <div class="spot_row">
      <% @city.spots[i..(i+4)].each do |spot| %>
        <%= link_to city_spot_path(@city, spot), class: "spot_link" do %>
          <div class="spot_img" style="background-image:url('<%= spot.image_url %>')"><p><%= spot.name %></p></div>
        <% end %>
      <% end %>
    </div>
    <% i += 5 %>
  <% end %>

  <div id='nav_links'>
    <%= link_to 'Edit', edit_city_path(@city) %> |
    <%= link_to 'Back', cities_path %>
  </div>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :spot_id %>
    <%= form.text_field :spot_id, id: :comment_spot_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Spot</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.spot %></td>
        <td><%= comment.user %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spot:</strong>
  <%= @comment.spot %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserCityspots01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='user_dashboard'>
      <div id='title_div'><a href='/'>City Spots</a></div>
      <% if user_signed_in? %>
        <p>Signed in as <strong><%= current_user.email %></strong> || <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></p>
      <% else %>
        <p><%= link_to 'Sign Up', new_user_registration_path %> ||
          <%= link_to 'Sign In', new_user_session_path %></p>
      <% end %>
    </div>
    <%= yield %>
    <%= javascript_include_tag "#{params[:controller]}/#{params[:action]}.js" if Rails.application.assets.resolve("#{params[:controller]}/#{params[:action]}.js").present? %>
  </body>
</html>

app/views/spots/_form.html.erb
<%= form_for [@city, @spot] do |form| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :spot_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :spot_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Edit This Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', city_spot_path(@spot) %> |
<%= link_to 'Back', city_spots_path %>

app/views/spots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <td><%= spot.name %></td>
        <td><%= spot.description %></td>
        <td><%= spot.city %></td>
        <td><%= link_to 'Show', city_spot %></td>
        <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
        <td><%= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>Submit a new Spot in <%= @city.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<style type="text/css">
  <%= raw Rails.application.assets['application.css'].to_s %>
</style>
<script type="text/javascript">
  <%= raw Rails.application.assets['application.js'].to_s %>
</script>

<p id="notice"><%= notice %></p>

<div id="spot_banner_title">
  <h2><%= @spot.name %></h2>
  <p><%= @spot.city.name %></p>
</div>

<div id="spot_banner" style="background-image:url('<%= @spot.image_url %>')"></div>


<div id="comments">
  <div id='comment_intro'><h3>Comments about <%= @spot.name %></h3></div> | <div id='comment_form_link'>New Comment</div>

  <div id="new_comment_form">
    <% if user_signed_in? %>
      <%= form_for [@city, @spot, Comment.new] do |f| %>
        <div class="field">
          <%= f.text_area :body, cols: 35, rows: 2 %><br>
          <%= f.submit %>
          <div class="btn" id="cancel_comment"> Cancel </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <% @spot.comments.order("created_at DESC").each do |comment| %>
    <div class="single_comment">
      <p id='comment_body'><%= comment.body %></p>
      <p id='comment_info'>Posted by <%= comment.user.email %> on <%= comment.created_at.strftime("%b %d, %Y") %></p>
      <% if comment.user == current_user %>
        <%= link_to "Delete", city_spot_comment_url(@city, @spot, comment), method: :delete %>
      <% end %>
    </div>
  <% end %>

</div>

<%= link_to 'Edit', edit_city_spot_path(@city, @spot) %> |
<%= link_to 'Back', city_path(@city) %>